In [3]:
import flowio
import numpy as np
flow_data = flowio.FlowData('../test_data/cytek_data/raw/MilliQ_SSC_thres500.fcs')
filtered_flow_data = flowio.FlowData('../test_data/cytek_data/filtered/MilliQ_SSC_thres500.fcs')

In [4]:
flow_array = np.reshape(flow_data.events, (-1, flow_data.channel_count))
filtered_flow_array = np.reshape(filtered_flow_data.events, (-1, filtered_flow_data.channel_count))

In [5]:
flow_data.file_size

973813080

In [6]:
filtered_flow_data.file_size

105601298

In [7]:
flow_array[:100]

array([[   0.      ,  653.      ,  921.47064 , ...,  634.7775  ,
         302.      ,  132.94751 ],
       [   1.      ,  648.      ,  374.09875 , ...,  277.33063 ,
         144.      ,    2.340625],
       [   2.      ,  533.      ,  286.09128 , ...,  231.65501 ,
          42.      ,  -23.071877],
       ...,
       [  14.      ,  603.      ,  363.265   , ..., -148.26189 ,
         -16.      , -198.15063 ],
       [  14.      ,  576.      ,  445.78876 , ...,  -69.817505,
         564.      ,  183.43814 ],
       [  14.      ,  806.      ,  525.4369  , ..., -292.24377 ,
         195.      ,  -36.71438 ]], dtype=float32)

In [8]:
flow_data.channels

{'1': {'PnN': 'Time'},
 '2': {'PnN': 'SSC-H'},
 '3': {'PnN': 'SSC-A'},
 '4': {'PnN': 'V1-H'},
 '5': {'PnN': 'V1-A'},
 '6': {'PnN': 'V2-H'},
 '7': {'PnN': 'V2-A'},
 '8': {'PnN': 'V3-H'},
 '9': {'PnN': 'V3-A'},
 '10': {'PnN': 'V4-H'},
 '11': {'PnN': 'V4-A'},
 '12': {'PnN': 'V5-H'},
 '13': {'PnN': 'V5-A'},
 '14': {'PnN': 'V6-H'},
 '15': {'PnN': 'V6-A'},
 '16': {'PnN': 'V7-H'},
 '17': {'PnN': 'V7-A'},
 '18': {'PnN': 'V8-H'},
 '19': {'PnN': 'V8-A'},
 '20': {'PnN': 'V9-H'},
 '21': {'PnN': 'V9-A'},
 '22': {'PnN': 'V10-H'},
 '23': {'PnN': 'V10-A'},
 '24': {'PnN': 'V11-H'},
 '25': {'PnN': 'V11-A'},
 '26': {'PnN': 'V12-H'},
 '27': {'PnN': 'V12-A'},
 '28': {'PnN': 'V13-H'},
 '29': {'PnN': 'V13-A'},
 '30': {'PnN': 'V14-H'},
 '31': {'PnN': 'V14-A'},
 '32': {'PnN': 'V15-H'},
 '33': {'PnN': 'V15-A'},
 '34': {'PnN': 'V16-H'},
 '35': {'PnN': 'V16-A'},
 '36': {'PnN': 'FSC-H'},
 '37': {'PnN': 'FSC-A'},
 '38': {'PnN': 'SSC-B-H'},
 '39': {'PnN': 'SSC-B-A'},
 '40': {'PnN': 'B1-H'},
 '41': {'PnN': 'B1-A'},
 

In [9]:
filtered_flow_data.channels

{'1': {'PnN': 'FSC-A'},
 '2': {'PnN': 'SSC-A'},
 '3': {'PnN': 'SSC-B-A'},
 '4': {'PnN': 'FSC-H'},
 '5': {'PnN': 'SSC-H'},
 '6': {'PnN': 'SSC-B-H'},
 '7': {'PnN': 'B2-H'},
 '8': {'PnN': 'B2-A'},
 '9': {'PnN': 'Time'}}

In [10]:
filtered_flow_data.text

{'beginanalysis': '0',
 'begindata': '8654',
 'beginstext': '0',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'endanalysis': '0',
 'enddata': '105601297',
 'endstext': '0',
 'mode': 'L',
 'nextdata': '0',
 'par': '9',
 'tot': '2933129',
 'p1b': '32',
 'p1e': '0,0',
 'p1g': '1.0',
 'p1r': '262144',
 'p1n': 'FSC-A',
 'p2b': '32',
 'p2e': '0,0',
 'p2g': '1.0',
 'p2r': '262144',
 'p2n': 'SSC-A',
 'p3b': '32',
 'p3e': '0,0',
 'p3g': '1.0',
 'p3r': '262144',
 'p3n': 'SSC-B-A',
 'p4b': '32',
 'p4e': '0,0',
 'p4g': '1.0',
 'p4r': '262144',
 'p4n': 'FSC-H',
 'p5b': '32',
 'p5e': '0,0',
 'p5g': '1.0',
 'p5r': '262144',
 'p5n': 'SSC-H',
 'p6b': '32',
 'p6e': '0,0',
 'p6g': '1.0',
 'p6r': '262144',
 'p6n': 'SSC-B-H',
 'p7b': '32',
 'p7e': '0,0',
 'p7g': '1.0',
 'p7r': '262144',
 'p7n': 'B2-H',
 'p8b': '32',
 'p8e': '0,0',
 'p8g': '1.0',
 'p8r': '262144',
 'p8n': 'B2-A',
 'p9b': '32',
 'p9e': '0,0',
 'p9g': '1.0',
 'p9r': '262144',
 'p9n': 'Time',
 'date': '02-Aug-2023',
 'btim': '13:35:02.45',
 'etim

In [11]:
filtered_flow_array[1, :10]

array([ 4.8269497e+03,  3.7409875e+02,  7.6647499e+01,  5.8700000e+03,
        6.4800000e+02,  1.7700000e+02,  4.9000000e+01, -1.2004750e+02,
        9.9999997e-05], dtype=float32)

In [12]:
flow_array[6, :10]

array([   3.     ,  686.     ,  384.1969 ,  -14.     , -117.56625,
        343.     ,  156.42064,  -37.     , -151.47188,  299.     ],
      dtype=float32)

In [13]:
interesting_channels = ['SSC-H']

In [14]:
test_meta = {'begindata': '14244       ',
 'enddata': '973813071   ',
 'beginanalysis': '0           ',
 'endanalysis': '0           ',
 'beginstext': '0           ',
 'endstext': '0           ',
 'mode': 'L',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'par': '83',
 'nextdata': '0',
 'timestep': '0.0001',
 'date': '02-Aug-2023',
 'btim': '13:35:02.45',
 'etim': '13:36:02.47',
 'op': 'LEKC',
 'inst': 'Cytekbio',
 'cyt': 'Aurora',
 'cytsn': 'NM1173SP',
 'p1b': '32',
 'p1e': '0,0',
 'p1n': 'SSC-H',
 'p1v': '2000',
 'p1r': '   4194304',
 'p1display': 'LIN',
 'p1type': 'Side_Scatter',
 'apply compensation': 'FALSE',
 'laser1name': 'Violet',
 'laser1delay': '-27.075',
 'laser1asf': '1.07',
 'laser2name': 'Blue',
 'laser2delay': '0',
 'laser2asf': '1.24',
 'laser3name': 'Red',
 'laser3delay': '26.825',
 'laser3asf': '1.07',
 'fsc asf': '1.52',
 'window extension': '0',
 'threshold': '(SSC,500)',
 'vol': '       20.36',
 'usersettingname': 'Optimal EV setting 20220822',
 'charset': 'utf-8',
 'fil': 'MilliQ_SSC_thres500.fcs',
 'creator': 'SpectroFlo 3.0.3',
 'proj': 'Experiment_134',
 'tubename': 'MilliQ_SSC_thres500',
 'flowrate': 'Low'}

In [15]:
from flowio.create_fcs import create_fcs

test_events=flow_array[:,0]
fh = open('data_set1.fcs', 'wb')
create_fcs(fh, test_events, interesting_channels, metadata_dict=test_meta)
fh.close()

In [16]:
new_filtered_data = flowio.FlowData('./data_set1.fcs')
new_filtered_array = np.reshape(new_filtered_data.events, (-1, new_filtered_data.channel_count))
new_filtered_array

array([[0.00000e+00],
       [1.00000e+00],
       [2.00000e+00],
       ...,
       [5.99484e+05],
       [5.99484e+05],
       [5.99485e+05]], dtype=float32)

In [17]:
new_filtered_data.text

{'beginanalysis': '0',
 'begindata': '1055',
 'beginstext': '0',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'endanalysis': '0',
 'enddata': '11733570',
 'endstext': '0',
 'mode': 'L',
 'nextdata': '0',
 'par': '1',
 'tot': '2933129',
 'p1b': '32',
 'p1e': '0,0',
 'p1g': '1.0',
 'p1r': '   4194304',
 'p1n': 'SSC-H',
 'timestep': '0.0001',
 'date': '02-Aug-2023',
 'btim': '13:35:02.45',
 'etim': '13:36:02.47',
 'op': 'LEKC',
 'inst': 'Cytekbio',
 'cyt': 'Aurora',
 'cytsn': 'NM1173SP',
 'p1v': '2000',
 'vol': '       20.36',
 'fil': 'MilliQ_SSC_thres500.fcs',
 'proj': 'Experiment_134',
 'p1display': 'LIN',
 'p1type': 'Side_Scatter',
 'apply compensation': 'FALSE',
 'laser1name': 'Violet',
 'laser1delay': '-27.075',
 'laser1asf': '1.07',
 'laser2name': 'Blue',
 'laser2delay': '0',
 'laser2asf': '1.24',
 'laser3name': 'Red',
 'laser3delay': '26.825',
 'laser3asf': '1.07',
 'fsc asf': '1.52',
 'window extension': '0',
 'threshold': '(SSC,500)',
 'usersettingname': 'Optimal EV setting 20220822

In [18]:
new_filtered_array.flatten()[:10]

array([0., 1., 2., 2., 2., 2., 3., 3., 3., 3.], dtype=float32)

In [19]:
np.max(new_filtered_array)

599485.0

In [20]:
test_events.max()

599485.0

In [21]:
4194304
262144

262144

# Rosetta

In [23]:
rosetta_data = flowio.FlowData('/Volumes/STORAGE/fcs_filter/raw/20231006_Rosetta_ME.fcs')
rosetta_data.text

{'begindata': '14264       ',
 'enddata': '237492535   ',
 'beginanalysis': '0           ',
 'endanalysis': '0           ',
 'beginstext': '0           ',
 'endstext': '0           ',
 'mode': 'L',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'par': '83',
 'tot': '715296',
 'nextdata': '0',
 'timestep': '0.0001',
 'date': '06-Oct-2023',
 'btim': '15:17:49.50',
 'etim': '15:19:41.03',
 'op': 'LEKC',
 'inst': 'Cytekbio',
 'cyt': 'Aurora',
 'cytsn': 'NM1173SP',
 'p1b': '32',
 'p1e': '0,0',
 'p1n': 'Time',
 'p1r': '   1116027',
 'p1display': 'LOG',
 'p1type': 'Time',
 'p2b': '32',
 'p2e': '0,0',
 'p2n': 'SSC-H',
 'p2v': '2000',
 'p2r': '   4194304',
 'p2display': 'LIN',
 'p2type': 'Side_Scatter',
 'p3b': '32',
 'p3e': '0,0',
 'p3n': 'SSC-A',
 'p3v': '2000',
 'p3r': '   4194304',
 'p3display': 'LIN',
 'p3type': 'Side_Scatter',
 'p4b': '32',
 'p4e': '0,0',
 'p4n': 'V1-H',
 'p4v': '2000',
 'p4r': '   4194304',
 'p4display': 'LOG',
 'p4type': 'Raw_Fluorescence',
 'p5b': '32',
 'p5e': '0,0',
 'p5n

In [33]:
rosetta_meta = {
 'beginanalysis': '0           ',
 'endanalysis': '0           ',
 'beginstext': '0           ',
 'endstext': '0           ',
 'mode': 'L',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'par': '83',
 'tot': '715296',
 'nextdata': '0',
 'timestep': '0.0001',
 'date': '06-Oct-2023',
 'btim': '15:17:49.50',
 'etim': '15:19:41.03',
 'op': 'LEKC',
 'inst': 'Cytekbio',
 'cyt': 'Aurora',
 'cytsn': 'NM1173SP',
 'p1b': '32',
 'p1e': '0,0',
 'p1n': 'Time',
 'p1r': '   1116027',
 'p1display': 'LOG',
 'p1type': 'Time',
 'p2b': '32',
 'p2e': '0,0',
 'p2n': 'SSC-H',
 'p2v': '2000',
 'p2r': '   4194304',
 'p2display': 'LIN',
 'p2type': 'Side_Scatter',
 'p3b': '32',
 'p3e': '0,0',
 'p3n': 'B2-H',
 'p3v': '2500',
 'p3r': '   4194304',
 'p3display': 'LOG',
 'p3type': 'Raw_Fluorescence',
 'apply compensation': 'FALSE',
 'laser1name': 'Violet',
 'laser1delay': '-27.025',
 'laser1asf': '1.07',
 'laser2name': 'Blue',
 'laser2delay': '0',
 'laser2asf': '1.24',
 'laser3name': 'Red',
 'laser3delay': '26.9',
 'laser3asf': '1.07',
 'fsc asf': '1.52',
 'window extension': '0',
 'threshold': '(SSC,1500)',
 'vol': '        23.8',
 'usersettingname': 'Optimal EV setting 20220822',
 'charset': 'utf-8',
 'fil': '20231006_Rosetta_ME.fcs',
 'creator': 'SpectroFlo 3.0.3',
 'proj': 'Experiment_160',
 'tubename': '20231006_Rosetta_ME',
 'groupname': 'Group_001',
 'flowrate': 'Low'}

In [34]:
rosetta_array = np.reshape(rosetta_data.events, (-1, rosetta_data.channel_count))
rosetta_array_filtered = rosetta_array[:, [0,1,41]]
rosetta_channels=['Time', 'SSC-H', 'B2-H']

In [35]:
rosetta_array_filtered.shape

(715296, 3)

In [36]:
fh = open('/Volumes/STORAGE/fcs_filter/filtered/20231006_Rosetta_ME_filtered.fcs', 'wb')
create_fcs(fh, rosetta_array_filtered.flatten(), rosetta_channels, metadata_dict=rosetta_meta)
fh.close()

In [37]:
new_rosetta_data = flowio.FlowData('/Volumes/STORAGE/fcs_filter/filtered/20231006_Rosetta_ME_filtered.fcs')
new_rosetta_array = np.reshape(new_rosetta_data.events, (-1, new_rosetta_data.channel_count))
new_rosetta_data.text

{'beginanalysis': '0',
 'begindata': '1250',
 'beginstext': '0',
 'byteord': '1,2,3,4',
 'datatype': 'F',
 'endanalysis': '0',
 'enddata': '8584801',
 'endstext': '0',
 'mode': 'L',
 'nextdata': '0',
 'par': '3',
 'tot': '715296',
 'p1b': '32',
 'p1e': '0,0',
 'p1g': '1.0',
 'p1r': '   1116027',
 'p1n': 'Time',
 'p2b': '32',
 'p2e': '0,0',
 'p2g': '1.0',
 'p2r': '   4194304',
 'p2n': 'SSC-H',
 'p3b': '32',
 'p3e': '0,0',
 'p3g': '1.0',
 'p3r': '   4194304',
 'p3n': 'B2-H',
 'timestep': '0.0001',
 'date': '06-Oct-2023',
 'btim': '15:17:49.50',
 'etim': '15:19:41.03',
 'op': 'LEKC',
 'inst': 'Cytekbio',
 'cyt': 'Aurora',
 'cytsn': 'NM1173SP',
 'p2v': '2000',
 'p3v': '2500',
 'vol': '        23.8',
 'fil': '20231006_Rosetta_ME.fcs',
 'proj': 'Experiment_160',
 'p1display': 'LOG',
 'p1type': 'Time',
 'p2display': 'LIN',
 'p2type': 'Side_Scatter',
 'p3display': 'LOG',
 'p3type': 'Raw_Fluorescence',
 'apply compensation': 'FALSE',
 'laser1name': 'Violet',
 'laser1delay': '-27.025',
 'laser1a